import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "./theme-provider";
import { ThemeSwitch } from "@/components/ThemeSwitch";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={`${inter.className} bg-slate-100 dark:bg-[#0A0C10]`} >
        <ThemeProvider attribute="class" defaultTheme1="system" enableSystem>
          <ThemeSwitch/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
